### ISSUE TITLE
关于内核页表的问题

### ISSUE THREAD

**Issue by longintlong** [huihongxiao/MIT6.S081#10]
感谢大佬的翻译和讲解，我想问大佬几个问题
1.就是课堂中，kernel page table将这个虚拟内存地址翻译成与之等价物理内存地址，这个等价是指什么？
2. “因为只有trampoline中代码是同时在用户和内核空间中映射”这句话如何理解

**Comment by huihongxiao** [comment]
> 感谢大佬的翻译和讲解，我想问大佬几个问题
> 1.就是课堂中，kernel page table将这个虚拟内存地址翻译成与之等价物理内存地址，这个等价是指什么？

在内核中使用的内存地址比如说A，并不是一个实际在RAM上的地址，但是A对应的数据必然存在RAM上的一个物理内存地址B。这里的等价就是指A通过kernel page table与B等价。

> 2. “因为只有trampoline中代码是同时在用户和内核空间中映射”这句话如何理解

trampoline是一个特殊的物理内存page，它即出现在内核Page Table中，也出现在用户Page Table中，也就是说在用户和内核都有虚拟内存地址与之对应，所以它同时映射在这两者的地址空间中。

**Comment by longintlong** [comment]
> > 感谢大佬的翻译和讲解，我想问大佬几个问题
> > 1.就是课堂中，kernel page table将这个虚拟内存地址翻译成与之等价物理内存地址，这个等价是指什么？
> 
> 在内核中使用的内存地址比如说A，并不是一个实际在RAM上的地址，但是A对应的数据必然存在RAM上的一个物理内存地址B。这里的等价就是指A通过kernel page table与B等价。
> 
> > 1. “因为只有trampoline中代码是同时在用户和内核空间中映射”这句话如何理解
> 
> trampoline是一个特殊的物理内存page，它即出现在内核Page Table中，也出现在用户Page Table中，也就是说在用户和内核都有虚拟内存地址与之对应，所以它同时映射在这两者的地址空间中。

感谢您的讲解！
所以是不是同时 内核页表的trapframe page 也和用户页表的trapframe page 映射到了同一块物理内存page，看代码中好像确实是这样。

**Comment by huihongxiao** [comment]
> 所以是不是同时 内核页表的trapframe page 也和用户页表的trapframe page 映射到了同一块物理内存page，看代码中好像确实是这样。

trapframe page是每个用户进程专有的，只是是由内核映射到用户页表中。不确定Linux是如何工作的，但是XV6中，每次使用trapframe都是在user page table下（参考6.5和6.8），但是是在内核模式下使用该page。所以合理的推论是trapframe可以每个用户进程使用不同的虚拟内存地址，并且必然映射到不同的物理内存地址。
内核并没有专门的trapframe page。

**Comment by longintlong** [comment]
> > 所以是不是同时 内核页表的trapframe page 也和用户页表的trapframe page 映射到了同一块物理内存page，看代码中好像确实是这样。
> 
> trapframe page是每个用户进程专有的，只是是由内核映射到用户页表中。不确定Linux是如何工作的，但是XV6中，每次使用trapframe都是在user page table下（参考6.5和6.8），但是是在内核模式下使用该page。所以合理的推论是trapframe可以每个用户进程使用不同的虚拟内存地址，并且必然映射到不同的物理内存地址。
> 内核并没有专门的trapframe page。

感谢大佬，确实如此，每个进程的trapframe page 都是不在一个物理页的，再次感谢！
