### ISSUE TITLE
6.4节的翻译问题

### ISSUE THREAD

**Issue by chen-zhuohan** [huihongxiao/MIT6.S081#11]
原文中有这么一段话

> 这里的控制是通过STVEC寄存器完成的，这是一个只能在supervisor mode下读写的特权寄存器。在从**用户空间进入到内核空间**之前，内核会设置好STVEC寄存器指向内核希望trap代码运行的位置。

这里说STVEC寄存器是内核设置的，那么是不是应该是“从**内核空间进入到用户空间**之前，内核会设置好STVEC寄存器”？

还有一处可能有问题的地方

> 切换page table的代价比较高，如果ecall打包完成了这部分工作，那就**不可能**对一些系统调用进行改进，使其不用在不必要的场景切换page table。

这里的这个**不可能**似乎有些不通畅？

**Comment by huihongxiao** [comment]
> 原文中有这么一段话
> 
> > 这里的控制是通过STVEC寄存器完成的，这是一个只能在supervisor mode下读写的特权寄存器。在从**用户空间进入到内核空间**之前，内核会设置好STVEC寄存器指向内核希望trap代码运行的位置。
> 
> 这里说STVEC寄存器是内核设置的，那么是不是应该是“从**内核空间进入到用户空间**之前，内核会设置好STVEC寄存器”？

的确。因为用户空间在最最最开始是从内核空间的代码进入的，在这个时候，内核会设置STVEC寄存器，这样当用户空间代码需要进入trap时，PC会跳转到STVEC寄存器的地址。
 
> 还有一处可能有问题的地方
> 
> > 切换page table的代价比较高，如果ecall打包完成了这部分工作，那就**不可能**对一些系统调用进行改进，使其不用在不必要的场景切换page table。
> 
> 这里的这个**不可能**似乎有些不通畅？
**不可能**改成了**不能**
